2019-12-27 20:36:23 WARN  DBService:217 - Unable to succesfully log in
2019-12-28 10:26:40 WARN  DBService:217 - Unable to succesfully log in
2019-12-28 10:30:22 WARN  DBService:217 - Unable to succesfully log in
2019-12-28 10:40:19 WARN  DBService:198 - Unable to retrieve information
org.postgresql.util.PSQLException: ERROR: relation "ers.reimbursements" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at ersapplication.DBService.getReimbursement(DBService.java:167)
	at ersapplication.System.getReimbursement(System.java:24)
	at ersapplication.Driver.main(Driver.java:10)
2019-12-28 11:12:01 WARN  DBService:198 - Unable to retrieve information
org.postgresql.util.PSQLException: ERROR: relation "ers.reimbursements" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at ersapplication.DBService.getReimbursement(DBService.java:167)
	at ersapplication.System.getReimbursement(System.java:24)
	at com.revature.main.Driver.main(Driver.java:12)
2019-12-28 11:13:54 WARN  DBService:198 - Unable to retrieve information
org.postgresql.util.PSQLException: ERROR: relation "ers.reimbursements" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at ersapplication.DBService.getReimbursement(DBService.java:167)
	at ersapplication.System.getReimbursement(System.java:24)
	at com.revature.main.Driver.main(Driver.java:12)
2019-12-28 11:16:14 WARN  DBService:194 - No reimbursement transaction was found for ID 1
2019-12-28 11:17:55 WARN  DBService:198 - Unable to retrieve information
org.postgresql.util.PSQLException: ERROR: relation "ers.reimbursements" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at ersapplication.DBService.getReimbursement(DBService.java:167)
	at ersapplication.System.getReimbursement(System.java:24)
	at com.revature.main.Driver.main(Driver.java:12)
2019-12-28 11:18:07 WARN  DBService:194 - No reimbursement transaction was found for ID 1
2019-12-28 11:19:55 WARN  DBService:194 - No reimbursement transaction was found for ID 1
2019-12-28 11:32:19 WARN  DBService:194 - No reimbursement transaction was found for ID 1
2019-12-28 11:36:30 WARN  DBService:198 - Unable to retrieve information
org.postgresql.util.PSQLException: ERROR: relation "ers.reimbursements" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at ersapplication.DBService.getReimbursement(DBService.java:167)
	at ersapplication.System.getReimbursement(System.java:24)
	at com.revature.main.Driver.main(Driver.java:13)
2019-12-28 11:43:12 INFO  DBService:165 - SELECT * FROM REIMBURSEMENTS WHERE REIMBURSEMENTS.REIMB_ID=?
2019-12-28 11:43:12 INFO  DBService:167 - SELECT * FROM REIMBURSEMENTS WHERE REIMBURSEMENTS.REIMB_ID=?
2019-12-28 11:43:12 INFO  DBService:170 - org.postgresql.jdbc.PgResultSet@6f75e721
2019-12-28 11:43:12 WARN  DBService:197 - No reimbursement transaction was found for ID 1
2019-12-28 11:48:39 INFO  DBService:168 - org.postgresql.jdbc.PgResultSet@123772c4
2019-12-28 11:48:39 WARN  DBService:195 - No reimbursement transaction was found for ID 1
2019-12-28 11:49:10 WARN  DBService:194 - No reimbursement transaction was found for ID 2
2019-12-28 11:58:33 WARN  DBService:194 - No reimbursement transaction was found for Reimbursement ID 2
2019-12-28 11:59:13 WARN  DBService:194 - No reimbursement transaction was found for Reimbursement ID 2
2019-12-28 12:05:54 WARN  DBService:194 - No reimbursement transaction was found for Reimbursement ID 2
2019-12-28 12:12:12 WARN  DBService:209 - No reimbursement transaction was found for Reimbursement ID 2
2019-12-28 12:14:38 WARN  DBService:194 - No reimbursement transaction was found for Reimbursement ID 2
2019-12-28 12:19:04 WARN  DBService:194 - No reimbursement transaction was found for Reimbursement ID 2
2019-12-28 12:19:58 WARN  DBService:72 - Unable to add user account
org.postgresql.util.PSQLException: ERROR: relation "ers.users" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at ersapplication.DBService.addUser(DBService.java:66)
	at ersapplication.Application.addUser(Application.java:16)
	at com.revature.main.Driver.main(Driver.java:11)
2019-12-28 12:36:54 WARN  DBService:72 - Unable to add user account
org.postgresql.util.PSQLException: ERROR: relation "ers.users" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at ersapplication.DBService.addUser(DBService.java:66)
	at ersapplication.Application.addUser(Application.java:16)
	at com.revature.main.Driver.main(Driver.java:11)
2019-12-28 13:51:55 WARN  DBService:44 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: database "ERS" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2617)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:135)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:250)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at ersapplication.DBService.connect(DBService.java:42)
	at ersapplication.DBService.addUser(DBService.java:55)
	at ersapplication.Application.addUser(Application.java:16)
	at com.revature.main.Driver.main(Driver.java:11)
2020-01-01 11:55:35 WARN  DBService:160 - Failed to retrieve reimbursements
org.postgresql.util.PSQLException: ERROR: column reimbursements.author does not exist
  Hint: Perhaps you meant to reference the column "reimbursements.author_id".
  Position: 42
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.ersapplication.DBService.getReimbursements(DBService.java:138)
	at com.revature.main.Driver.main(Driver.java:25)
2020-01-01 12:12:03 WARN  DBService:160 - Failed to retrieve reimbursements
org.postgresql.util.PSQLException: Bad value for type int : Lodging
	at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2858)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2067)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.ersapplication.DBService.getReimbursements(DBService.java:150)
	at com.revature.main.Driver.main(Driver.java:25)
2020-01-01 12:12:17 WARN  DBService:160 - Failed to retrieve reimbursements
org.postgresql.util.PSQLException: Bad value for type int : Lodging
	at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2858)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2067)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.ersapplication.DBService.getReimbursements(DBService.java:150)
	at com.revature.main.Driver.main(Driver.java:25)
2020-01-01 12:25:46 WARN  DBService:160 - Failed to retrieve reimbursements
org.postgresql.util.PSQLException: Bad value for type int : Lodging
	at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2858)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2067)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.ersapplication.DBService.getReimbursements(DBService.java:150)
	at com.revature.main.Driver.main(Driver.java:25)
2020-01-01 14:29:40 WARN  DBService:160 - Failed to retrieve reimbursements
org.postgresql.util.PSQLException: Bad value for type int : Lodging
	at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2858)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2067)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.ersapplication.DBService.getReimbursements(DBService.java:150)
	at com.revature.main.Driver.main(Driver.java:25)
2020-01-01 14:57:02 WARN  DBService:160 - Failed to retrieve reimbursements
org.postgresql.util.PSQLException: Bad value for type int : Lodging
	at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2858)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2067)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.ersapplication.DBService.getReimbursements(DBService.java:150)
	at com.revature.main.Driver.main(Driver.java:25)
2020-01-02 20:01:06 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: column "author" of relation "reimbursements" does not exist
  Position: 97
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:06:14 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: INSERT has more target columns than expressions
  Position: 129
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:08:38 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:16:10 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:35:11 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:40:58 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:44:27 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:44:42 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:44:50 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:49:39 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:54:32 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 20:58:03 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 21:05:20 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:10)
2020-01-02 21:07:12 WARN  DBService:98 - Unable to add reimbursement request
org.postgresql.util.PSQLException: ERROR: insert or update on table "reimbursements" violates foreign key constraint "reimbursements_resolver_fkey"
  Detail: Key (resolver)=(0) is not present in table "users".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.ersapplication.DBService.addReimbursement(DBService.java:93)
	at com.revature.ersapplication.Application.addReimbursement(Application.java:133)
	at com.revature.main.Driver.main(Driver.java:11)
